export const CONTENT_IDEAS = [
  "Evolusi teknologi tambang emas: dari dulang manual hingga otomatisasi AI",
  "Proses kimiawi pemisahan emas dari bebatuan menggunakan sianida",
  "Bagaimana aktivitas vulkanik jutaan tahun lalu membentuk urat emas di perut bumi",
  "Dampak ekonomi vs lingkungan dari tambang emas skala besar",
  "Sejarah demam emas (Gold Rush) dan kota-kota mati yang ditinggalkan",
  "Penambangan emas dari limbah elektronik (e-waste) dan motherboard komputer",
  "Bagaimana emas terbentuk dari tabrakan bintang neutron di luar angkasa",
  "Transportasi material tambang emas menggunakan truk raksasa otonom",
  "Pemurnian emas 99.99% di pabrik peleburan bersuhu 1000 derajat Celcius",
  "Kehidupan sehari-hari pekerja tambang emas di bawah tanah sedalam 3 kilometer",
  "Mengapa emas tidak bisa berkarat dan tahan terhadap sebagian besar asam",
  "Cara kerja alat metal detector modern dalam mendeteksi nugget emas",
  "Peran tumbuhan tertentu yang bisa menyerap partikel emas dari tanah",
  "Pencarian harta karun kapal karam yang berisi berton-ton koin emas",
  "Bagaimana emas digunakan dalam komponen satelit dan pesawat luar angkasa",
  "Teknik tradisional menambang emas menggunakan metode amalgamasi merkuri",
  "Bahaya paparan merkuri bagi penambang emas skala kecil",
  "Eksplorasi cadangan emas menggunakan citra satelit dan geofisika",
  "Apa yang terjadi jika cadangan emas di bumi benar-benar habis?",
  "Mitos dan fakta tentang kota emas legendaris El Dorado",
  "Perbandingan nilai investasi emas fisik versus emas digital",
  "Bagaimana cara membedakan emas asli dan emas palsu secara ilmiah",
  "Tambang emas Grasberg Papua: Salah satu tambang terbesar di dunia",
  "Proses pembuatan perhiasan emas dengan teknik 3D printing modern",
  "Mengapa bank sentral di seluruh dunia menyimpan ribuan ton emas batangan",
  "Penambangan emas purba pada masa kekaisaran Romawi dan Mesir kuno",
  "Rahasia di balik brankas emas terbesar di dunia di Federal Reserve New York",
  "Cara merestorasi artefak emas kuno yang terkubur ribuan tahun",
  "Emas putih, emas mawar (rose gold), dan logam paduan emas lainnya",
  "Apakah mungkin membuat emas di laboratorium seperti ahli alkimia? (Reaktor nuklir)",
  "Pemanfaatan emas dalam dunia medis modern dan pengobatan kanker",
  "Ekstraksi emas menggunakan teknologi bioleaching dengan bantuan bakteri",
  "Bagaimana nanopartikel emas digunakan dalam teknologi panel surya",
  "Sejarah standar emas (Gold Standard) dalam sistem keuangan global",
  "Misteri kereta emas Nazi yang hilang di Polandia",
  "Mengapa emas bisa diubah menjadi lembaran sangat tipis (gold leaf)?",
  "Proses terjadinya emas aluvial di sepanjang aliran sungai",
  "Cara penambang rakyat menggunakan pompa hisap di dasar sungai",
  "Analisis dampak lingkungan dari tailing (limbah buangan) tambang emas",
  "Drone bawah tanah untuk pemetaan terowongan tambang emas",
  "Operasi penyelamatan ambruknya terowongan tambang emas",
  "Bagaimana emas digunakan dalam industri kosmetik dan perawatan kulit",
  "Kandungan emas di lautan: Mengapa kita tidak menambangnya?",
  "Peran perempuan dalam industri pertambangan emas modern",
  "Jejak karbon dari produksi satu ons emas",
  "Penggunaan emas dalam kaca helm astronot untuk menolak radiasi matahari",
  "Teknik 'fire assay' untuk menguji kadar kemurnian emas secara presisi",
  "Emas dalam budaya manusia: Dari mahkota raja hingga medali olimpiade",
  "Cara mengolah lapisan emas dari kartu SIM smartphone bekas",
  "Tambang emas bawah laut: Potensi dan ancaman bagi ekosistem laut",
  "Konflik berlian dan tambang emas: Isu hak asasi manusia di negara konflik",
  "Bagaimana emas membantu perkembangan mikrochip kecerdasan buatan",
  "Reklamasi lahan bekas tambang emas menjadi hutan lindung kembali",
  "Fenomena 'fools gold' (Pirit) yang sering mengecoh penambang emas",
  "Rantai pasokan emas: Dari lubang tambang hingga etalase toko perhiasan",
  "Eksplorasi emas di asteroid: Mungkinkah di masa depan?",
  "Bagaimana sensor seismik memprediksi area kaya deposit emas",
  "Penambangan emas epithermal di daerah pegunungan vulkanik aktif",
  "Karat pada emas: Perbedaan emas 18K, 22K, dan 24K secara molekuler",
  "Emas yang dapat dikonsumsi: Tren kuliner mewah dengan lembaran emas",
  "Regulasi ketat pemerintah terhadap izin pembukaan lahan tambang emas",
  "Inovasi hijau di sektor pertambangan: Tambang emas tanpa emisi",
  "Proses smelting: Pembakaran bijih emas mentah di tanur raksasa",
  "Emas dalam agama dan mitologi: Simbol keabadian dan dewa matahari",
  "Cerita sukses dan kejatuhan para pencari emas di Klondike abad ke-19",
  "Penemuan nugget emas terbesar di dunia 'Welcome Stranger' di Australia",
  "Risiko ledakan gas metana di terowongan tambang emas tertutup",
  "Bagaimana air hujan bisa menyebarkan partikel emas mikroskopis di tanah",
  "Teknologi X-ray fluorescence (XRF) untuk analisis bijih emas di lapangan",
  "Pengolahan air sisa tambang emas sebelum dikembalikan ke alam",
  "Mengukur ukuran cadangan emas dunia yang belum ditambang",
  "Perbedaan menambang emas cebakan primer (vein) dan sekunder (placer)",
  "Mengapa penambang emas tradisional masih bertahan di era modern?",
  "Proses pembuatan benang emas untuk pakaian tradisional mewah",
  "Keunikan kristal emas asli yang tumbuh secara alami di bebatuan",
  "Bagaimana emas digunakan untuk melapisi kaca gedung pencakar langit",
  "Operasi keamanan tingkat tinggi di area pertambangan dan transportasi emas",
  "Tambang emas Mponeng Afrika Selatan: Menjelajahi kedalaman 4 kilometer",
  "Penyelundupan emas ilegal antar negara dan upaya pencegahannya",
  "Pengaruh fluktuasi harga emas dunia terhadap ekonomi lokal penambang",
  "Perbandingan efisiensi tambang emas open-pit versus underground mining",
  "Peran robot pengebor otomatis di area tambang rawan longsor",
  "Cara masyarakat adat mengelola tambang emas dengan kearifan lokal",
  "Pembentukan emas melalui sirkulasi hidrotermal bawah laut purba",
  "Bagaimana emas melindungi pesawat jet dari gangguan elektromagnetik",
  "Pengukuran kandungan emas dalam satuan Part Per Million (PPM)",
  "Tantangan menambang emas di iklim ekstrem seperti Siberia dan Alaska",
  "Pemanfaatan limbah tambang (tailing) untuk bahan bangunan dan paving",
  "Tren perhiasan emas daur ulang (recycled gold) yang ramah lingkungan",
  "Eksperimen yang membuktikan emas bisa menghantarkan listrik tanpa hambatan",
  "Sejarah teknik cyanidation yang mengubah wajah industri pertambangan",
  "Proses pendinginan batangan emas setelah dicetak dalam suhu ribuan derajat",
  "Emas dalam pengobatan Ayurveda tradisional sebagai 'Swarna Bhasma'",
  "Misteri deposit emas di cekungan Witwatersrand Afrika Selatan",
  "Pelatihan khusus tim penyelamat (rescue team) pertambangan bawah tanah",
  "Mengapa banyak penemuan tambang emas berawal dari mineral tembaga?",
  "Evolusi alat pendulang emas dari wajan kayu hingga mesin trommel modern",
  "Jejak geologi emas di Indonesia: Dari Sumatera hingga Papua",
  "Dampak pemanasan global terhadap pencairan es (permafrost) yang menyimpan emas",
  "Masa depan uang fisik: Apakah kita akan kembali ke mata uang berbasis emas?"
];
